### PR TITLE
Fix #195 servlet-api updated to 3.0 to fix classpath issue with old servlet-api-2.5 and old json-path

### LINKED ISSUE #195: Classpath issue with old servlet-api-2.5 and old json-path.
With **wiremock-standalone-1.52** and **mockMvc** I have exception in test:

```
NoSuchMethodError: javax.servlet.http.HttpServletRequest.isAsyncStarted()Z
    at org.springframework.test.web.servlet.result.PrintingResultHandler.printAsyncResult(PrintingResultHandler.java:131)
    at org.springframework.test.web.servlet.result.PrintingResultHandler.handle(PrintingResultHandler.java:80)
    at org.springframework.test.web.servlet.MockMvc$1.andDo(MockMvc.java:159)
```

I can't exclude this old `HttpServletRequest` from `servlet-api-2.5`, because it is included in `wiremock-standalone`. Wiremock should work with `servlet-api-3.0` too.

With standard **wiremock-1.52** I can exclude `servlet-api-2.5` and attach new `servlet-api-3.0`, but there is problem with old json-path:

```
com.jayway.jsonpath.JsonPath.read(Ljava/lang/String;Ljava/lang/String;[Lcom/jayway/jsonpath/Filter;)Ljava/lang/Object;</pre></p><h3>Caused by:</h3><pre>java.lang.NoSuchMethodError: com.jayway.jsonpath.JsonPath.read(Ljava/lang/String;Ljava/lang/String;[Lcom/jayway/jsonpath/Filter;)Ljava/lang/Object;
    at com.github.tomakehurst.wiremock.matching.ValuePattern.isJsonPathMatch(ValuePattern.java:194)
```

I think we should update `jsonPath` version, what is the reason for using old version?

### PR DESCRIPTION
**Pull request by mariuszs**

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
@tomakehurst - any progress with this?

**Comment by tomakehurst** [comment]
Closing as we're at Servlet 3.0 in WireMock 2.x
