### ISSUE TITLE
Please use the Map interface instead of ConcurrentHashMap in ThreadSafeRequestDelayControl to keep the java7 and java6 support

### ISSUE THREAD

**Issue by nikolavp** [tomakehurst/wiremock#309]
We got this lately

```bash
java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
	at com.github.tomakehurst.wiremock.global.ThreadSafeRequestDelayControl.cancelAllDelays(ThreadSafeRequestDelayControl.java:51)
	at com.github.tomakehurst.wiremock.global.ThreadSafeRequestDelayControl.clearDelay(ThreadSafeRequestDelayControl.java:38)
	at com.github.tomakehurst.wiremock.core.WireMockApp.resetMappings(WireMockApp.java:141)
	at com.github.tomakehurst.wiremock.WireMockServer.resetMappings(WireMockServer.java:293)
```

There is an explanation of why this exception is thrown at https://gist.github.com/AlainODea/1375759b8720a3f9f094. Please just use the Map interface in the declaration at ThreadSafeRequestDelayControl. I just checked and the class is not using any of the special methods in the ConcurrentMap.

**Comment by tomakehurst** [comment]
Presume you're using v1.57? If so, I built this version with jdk8 not realising it caused this problem.

Could you try 2.0.4-beta? I've been building the beta branch exclusively on jdk7 so it shouldn't exhibit this problem.

**Comment by JayeshS** [comment]
@tomakehurst Yes, it works in 2.0.4-beta

**Comment by nikolavp** [comment]
If you are not going to support the 1.x version, feel free to close this. I monkey patched it in our test until we move to 2.x.

**Comment by tomakehurst** [comment]
Sure, thanks.

The plan is to get 2.x out of beta pretty soon. The main impediment is a resource leak I've discovered. If i can't get that fixed soon I'll release a 1.58 with Java 7 support properly restored.

**Comment by tomakehurst** [comment]
I've just released v1.58, which just fixes this problem.

**Comment by nikolavp** [comment]
Nice one!
