### ISSUE TITLE
java.lang.NoSuchMethodError Exception after upgrading the wiremock version

### ISSUE THREAD

**Issue by OllyAndJo** [tomakehurst/wiremock#873]
Hi Tom, I am getting the below exception after upgrading the wiremock version to 2.14.0 without any code change, please advice, 
java.lang.NoSuchMethodError: com.github.tomakehurst.wiremock.client.WireMock.urlPathEqualTo(Ljava/lang/String;)Lcom/github/tomakehurst/wiremock/client/UrlMatchingStrategy;

**Comment by OllyAndJo** [comment]
code snippet for reference,


   public static void verifyGetVehicle(String platformVehicleIdentifier) {
      verifyWireMock(1, WireMock.getRequestedFor(urlPathEqualTo(String.format(Locale.ENGLISH, "/vehicles/%s", platformVehicleIdentifier))), 5000L);

   }

   private static void verifyWireMock(int count, RequestPatternBuilder requestBuilder, long timeout) {
      boolean ok = false;
      VerificationException lastException = null;

      long endTime = System.currentTimeMillis() + timeout;
      while (!ok && System.currentTimeMillis() < endTime) {
         try {
            WireMock.verify(count, requestBuilder);
            return;
         } catch (VerificationException exception) {
            try {
               lastException = exception;
               Thread.sleep(500L);
            } catch (InterruptedException ex) {
            }
         }
      }

      throw new RuntimeException("Could not verify mock before timeout", lastException);
   }

**Comment by tomakehurst** [comment]
Looks like you've somehow got two different WireMock versions in your classpath. Suggest doing a dependency dump from your build tool.

**Comment by OllyAndJo** [comment]
Thanks! @tomakehurst
